# Generated by Django 3.2.4 on 2022-10-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawNum', models.CharField(max_length=50, unique=True, verbose_name='开奖期号')),
                ('frontNum1', models.IntegerField()),
                ('frontNum2', models.IntegerField()),
                ('frontNum3', models.IntegerField()),
                ('frontNum4', models.IntegerField()),
                ('frontNum5', models.IntegerField()),
                ('backNum1', models.IntegerField()),
                ('backNum2', models.IntegerField()),
                ('drawTime', models.DateField(verbose_name='开奖日期')),
                ('isDeleted', models.BooleanField(default=0)),
                ('createdBy', models.CharField(max_length=100, null=True)),
                ('updateBy', models.CharField(max_length=100, null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'lottery_info',
            },
        ),
        migrations.CreateModel(
            name='LotterySelectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontNum1', models.IntegerField()),
                ('frontNum2', models.IntegerField()),
                ('frontNum3', models.IntegerField()),
                ('frontNum4', models.IntegerField()),
                ('frontNum5', models.IntegerField()),
                ('backNum1', models.IntegerField()),
                ('backNum2', models.IntegerField()),
                ('selectState', models.CharField(max_length=100)),
                ('isDeleted', models.BooleanField()),
                ('createdBy', models.CharField(max_length=100)),
                ('updateBy', models.CharField(max_length=100)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'lottery_select',
            },
        ),
    ]
