# Generated by Django 3.2.4 on 2022-10-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawNum', models.CharField(max_length=50, unique=True, verbose_name='开奖期号')),
                ('frontNum1', models.CharField(max_length=50)),
                ('frontNum2', models.CharField(max_length=50)),
                ('frontNum3', models.CharField(max_length=50)),
                ('frontNum4', models.CharField(max_length=50)),
                ('frontNum5', models.CharField(max_length=50)),
                ('backNum1', models.CharField(max_length=50)),
                ('backNum2', models.CharField(max_length=50)),
                ('drawTime', models.DateField(verbose_name='开奖日期')),
                ('isDeleted', models.BooleanField(default=0)),
                ('createdBy', models.CharField(max_length=100, null=True)),
                ('updateBy', models.CharField(max_length=100, null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'lottery_info',
            },
        ),
        migrations.CreateModel(
            name='LotterySelectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontNum1', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35')], max_length=50)),
                ('frontNum2', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35')], max_length=50)),
                ('frontNum3', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35')], max_length=50)),
                ('frontNum4', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35')], max_length=50)),
                ('frontNum5', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35')], max_length=50)),
                ('backNum1', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=50)),
                ('backNum2', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=50)),
                ('selectState', models.CharField(max_length=100, null=True)),
                ('isDeleted', models.BooleanField()),
                ('createdBy', models.CharField(max_length=100, null=True)),
                ('updateBy', models.CharField(max_length=100, null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'lottery_select',
            },
        ),
        migrations.CreateModel(
            name='LotteryWebhookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hookUrl', models.TextField()),
                ('isDeleted', models.BooleanField()),
                ('createdBy', models.CharField(max_length=100, null=True)),
                ('updateBy', models.CharField(max_length=100, null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'lottery_webhook',
            },
        ),
    ]
