name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test tags'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./easyLottery/lottery/compose/production/django/Dockerfile_dockerio
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          winspain0/easy_lottery:${{ steps.date.outputs.today }}
          winspain0/easy_lottery:latest

          
