name: Docker Image CI

on:
  push:
    tags:
      - v*

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test tags'

jobs:
  buildx:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get current date
      id: getTime
      run: echo "nowtime=$(TZ=Asia/Shanghai date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: lotteryGo/Dockerfile
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          winspain0/easy_lottery:v2.0.0
          winspain0/easy_lottery:latest

          
